version: '3'

services:
  db:
    container_name: db_room
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.room
  web:
    container_name: web_room
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.room
    depends_on:
      - db
