# Generated by Django 5.1 on 2024-08-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('current_participants', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('player1', models.CharField(editable=False, max_length=20, null=True)),
                ('player2', models.CharField(editable=False, max_length=20, null=True)),
                ('player3', models.CharField(editable=False, max_length=20, null=True)),
                ('player4', models.CharField(editable=False, max_length=20, null=True)),
                ('isPlaying', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
