# Generated by Django 5.1 on 2024-08-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player4',
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_participants',
            field=models.IntegerField(default=0),
        ),
    ]
