# Generated by Django 5.1 on 2024-08-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_player1_remove_room_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_participants',
            field=models.IntegerField(choices=[(2, '2 players'), (4, '4 players')]),
        ),
    ]
