# Generated by Django 5.1 on 2024-08-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ready_participants',
            field=models.IntegerField(default=0),
        ),
    ]
